# @package eval.tofu.metrics.BIO_Prob
defaults:
  - ../../data/datasets@datasets: TOFU_QA_BIO
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

batch_size: 16