# @package eval.tofu.metrics.forget_Q_A_PERT_ROUGE
defaults:
  - ../../data/datasets@datasets: TOFU_QA_forget_pert
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  # ^ get default dataset and generation config information

handler: rouge
batch_size: 32
datasets: # override as needed
  TOFU_QA_forget_pert:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left