# @package eval.tofu.metrics.forget_Q_A_Prob
defaults:
  - ../../data/datasets@datasets: TOFU_QA_FORGET10
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: 16