# @package eval.tofu.metrics.forget_Q_A_ROUGE
defaults:
  - ../../data/datasets@datasets: TOFU_QA_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  
  # ^ get default dataset and generation config information

handler: rouge
batch_size: 64
datasets: # override as needed
  TOFU_QA_forget:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left