# @package eval.tofu.metrics.full_BIO_ROUGE
defaults:
  - ../../data/datasets@datasets: TOFU_QA_BIO
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  # ^ get default dataset and generation config information

handler: rouge
batch_size: 32
generation_args:
  max_new_tokens: 1024
datasets: # override as needed
  TOFU_QA_BIO:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left