# @package eval.tofu.metrics.full_BIO_Prob
defaults:
  - ../../data/datasets@datasets: TOFU_QA_BIO
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: 32