defaults:
  - _default_generation_args
  - _default_collator_generation
  - ../../data@data_cfg: TOFU_QA_FORGET10_P
  # ^ get default dataset and generation config information

batch_size: 16
data_cfg: # override as needed
  TOFU_QA_FORGET10_P:
    args:
      predict_with_generate: True

