defaults:
  - ../../data@dataset_cfgs: TOFU_QA_FORGET10_PT
  - ../../collator@collator_cfgs: DataCollatorForSupervisedDatasetWithIndex
  # ^ get default dataset and generation config information

batch_size: 16