# @package eval.tofu.metrics.Q_A_PARA_Prob
defaults:
  - ../../data/datasets@datasets: TOFU_QA_FORGET10_P
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

handler: probability
batch_size: 16