defaults:
  - _default_generation_args
  - ../../data@data_cfg: TOFU_QA_FORGET10_PT
  # ^ get default dataset and generation config information

batch_size: 16
data_cfg: # override as needed
  TOFU_QA_FORGET10_PT:
    args:
      predict_with_generate: True