# @package eval.tofu.metrics.Q_A_PERT_Prob
defaults:
  - ../../data/datasets@datasets: TOFU_QA_FORGET10_PT
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  # ^ get default dataset and generation config information

batch_size: 16