# @package eval.tofu.metrics.Q_PARA_A_PARA_ROUGE
defaults:
  - ../../data/datasets@datasets: TOFU_QA_FORGET10_P
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  # ^ get default dataset and generation config information

batch_size: 16
datasets: # override as needed
  TOFU_QA_FORGET10_P:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left