defaults:
  - ../../data@data_cfg: TOFU_QA_FORGET10_P
  - ../../collator@collator_cfg: DataCollatorForSupervisedDatasetWithIndex
  # ^ get default dataset and generation config information

batch_size: 16