# @package eval.tofu.metrics.truth_ratio
defaults:
  - .@pre_compute.Q_A_PARA_Prob: Q_A_PARA_Prob
  - .@pre_compute.Q_A_PERT_Prob: Q_A_PERT_Prob

pre_compute:
  Q_A_PARA_Prob:
    access_key: paraphrase
  Q_A_PERT_Prob:
    access_key: perturb

handler: truth_ratio
