data_processing_args: &data_processing_args
  batch_size: 16
  collator_cfg:
    ${../collator/DataCollatorForSupervisedDatasetWithIndex.yaml}

generation_args: &generation_args
  do_sample: False
  max_new_tokens: 200
  use_cache: True