# @package eval.tofu
# NOTE: the above line is not a comment, but sets the package for config. See https://hydra.cc/docs/upgrades/0.11_to_1.0/adding_a_package_directive/

defaults:
  - tofu_metrics:
    - forget_knowmem_ROUGE
    - retain_knowmem_ROUGE

handler: MUSEEvaluator
device: cuda
output_dir: ${paths.output_dir} # set to default eval directory
metrics: {}
overwrite: false