tofu:
  metrics_cfg: 
    TOFU_Q_A_Prob:
      batch_size: 16
    TOFU_Q_PARA_A_PARA_Prob:
      batch_size: 16
    TOFU_Q_A_PERT_Prob:
      batch_size: 16
    TOFU_Q_A_ROUGE:
      batch_size: 16
      generation_args:
        do_sample: False
        max_new_tokens: 200
        use_cache: True
    TOFU_Q_PARA_A_PARA_ROUGE:
      batch_size: 16
      generation_args:
        do_sample: False
        max_new_tokens: 200
        use_cache: True
    TOFU_Q_A_PARA_ROUGE:
      batch_size: 16
      generation_args:
        do_sample: False
        max_new_tokens: 200
        use_cache: True
    TOFU_Q_A_PERT_ROUGE:
      batch_size: 16
      generation_args:
        do_sample: False
        max_new_tokens: 200
        use_cache: True
    TOFU_BIO_Prob:
      batch_size: 16
    TOFU_BIO_ROUGE:
      batch_size: 16
      generation_args:
        do_sample: False
        max_new_tokens: 1024
        use_cache: True
  device: cuda
  output_dir: evals
