defaults: # get data_processing_args and generation_args common to most metrics
  - defaults.yaml
tofu:
  metrics_cfg:
    TOFU_Q_A_Prob:
      <<: *data_processing_args
      data_cfg:
        ${../data/TOFU_QA_FORGET10.yaml}

    TOFU_Q_PARA_A_PARA_Prob:
      <<: *data_processing_args
      data_cfg:
        ${../data/TOFU_QA_FORGET10_P.yaml}

    TOFU_Q_A_PERT_Prob:
      <<: *data_processing_args
      data_cfg:
        ${../data/TOFU_QA_FORGET10_PT.yaml}

    TOFU_BIO_Prob:
      <<: *data_processing_args
      data_cfg:
        ${../data/TOFU_QA_BIO.yaml}

    TOFU_Q_A_ROUGE:
      <<: [*data_processing_args, *generation_args]
      data_cfg:
        ${../data/TOFU_QA_FORGET10.yaml}

    TOFU_Q_PARA_A_PARA_ROUGE:
      <<: [*data_processing_args, *generation_args]
      data_cfg:
        ${../data/TOFU_QA_FORGET10_P.yaml}

    TOFU_Q_A_PARA_ROUGE:
      <<: [*data_processing_args, *generation_args]
      data_cfg:
        ${../data/TOFU_QA_FORGET10_PT.yaml}

    TOFU_Q_A_PERT_ROUGE:
      <<: [*data_processing_args, *generation_args]
      data_cfg:
        ${../data/TOFU_QA_FORGET10_PT.yaml}

    TOFU_BIO_ROUGE:
      <<: [*data_processing_args, *generation_args]
      data_cfg:
        ${../data/TOFU_QA_BIO.yaml}
      generation_args: # override
        max_new_tokens: 1024

  device: cuda
  output_dir: evals