name: gemma-7b-it
model_args:
  pretrained_model_name_or_path: "google/gemma-7b-it"
  attn_implementation: 'flash_attention_2'
tokenizer_args:
  pretrained_model_name_or_path: "google/gemma-7b-it"
chat_templating:
  apply_chat_template: True
  system_role: False
