model_args:
  pretrained_model_name_or_path: "google/gemma-7b-it"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "google/gemma-7b-it"
template_args:
  apply_chat_template: True
