name: "Llama-3.1-8B-Instruct"
model_args:
  pretrained_model_name_or_path: "meta-llama/Llama-3.1-8B-Instruct"
tokenizer_args:
  pretrained_model_name_or_path: "meta-llama/Llama-3.1-8B-Instruct"
chat_templating:
  apply_chat_template: True
  system_role: True
attention: flash_attention_2