model_args:
  pretrained_model_name_or_path: "microsoft/Phi-3.5-mini-instruct"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "microsoft/Phi-3.5-mini-instruct"
template_args:
  apply_chat_template: False
  user_start_tag: "<|system|>\nYou are a helpful assistant.<|end|>\n<|user|>"
  user_end_tag: "<|end|>\n"
  asst_tag: "<|assistant|>\n"