defaults:
  - model: Llama-3.1-8B-Instruct
  - trainer: finetune
  - data: finetune
  - collator: DataCollatorForSupervisedDataset
  - eval: tofu
  - hydra: default
  - paths: default
  - _self_

mode: train