defaults:
  - model: Llama-3.2-3B-Instruct
  - trainer: finetune
  - data: finetune
  - collator: DataCollatorForSupervisedDataset
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null
  - _self_

mode: train
task_name: llama-3.2-8B_tofu_full