defaults:
  - model: Llama-3.1-8B-Instruct
  - trainer: GradAscent
  - data: unlearn
  - collator: DataCollatorForSupervisedDataset
  - hydra: default
  - paths: default

  - _self_

trainer:
  args: 
    remove_unused_columns: False

mode: unlearn