# @package eval.muse.metrics.forget_knowmem_ROUGE
defaults:
  - ../../data/datasets@datasets: MUSE_news_forget_qa
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
  
  # ^ get default dataset and generation config information

handler: rouge
batch_size: 32
datasets: # override as needed
  TOFU_QA_forget_para:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left
