# @package eval.muse.metrics.forget_minKpc_neg_logprob
defaults:
  - ../../data/datasets@datasets: MUSE_news_forget_privleak
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
handler: minKpc_negative_logprob
batch_size: 16
percentile_K: 40
