# @package eval.muse.metrics.forget_verbmem_ROUGE
defaults:
  - ../../data/datasets@datasets: MUSE_news_forget_snippets
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
handler: rouge
batch_size: 16
datasets: # override as needed
  MUSE_news_forget_snippets:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left
generation_args:
  max_new_tokens: 128
