# @package eval.muse.metrics.forget_knowmem_ROUGE
defaults:
  - ../../data/datasets@datasets: MUSE_news_forget_qa
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
handler: rouge
rouge_type: rougeL_f1
batch_size: 32
datasets:
  MUSE_news_forget_qa:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left
generation_args:
  max_new_tokens: 32
  stopwords: ["\n\n", "\nQuestion", "Question:"]
