# @package eval.muse.metrics.holdout_minKpc_prob
defaults:
  - ../../data/datasets@datasets: MUSE_news_holdout_privleak
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
handler: minKpc_probability
batch_size: 16
percentile: 40
