# @package eval.muse.metrics.holdout_minKpc_neg_logprob
defaults:
  - ../../data/datasets@datasets: MUSE_news_holdout_privleak
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
handler: minKpc_negative_logprob
batch_size: 16
percentile: 40
