# @package eval.muse.metrics.privleak
defaults:
  - .@pre_compute.forget_minKpc_neg_logprob: forget_minKpc_neg_logprob
  - .@pre_compute.holdout_minKpc_neg_logprob: holdout_minKpc_neg_logprob

pre_compute:
  forget_minKpc_neg_logprob:
    access_key: forget
  holdout_minKpc_neg_logprob:
    access_key: holdout
handler: rel_auc
ref_value:  0.5
