# @package eval.muse.metrics.retain_knowmem_ROUGE
defaults:
  - ../../data/datasets@datasets: MUSE_news_retain_qa
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: default
handler: rouge
batch_size: 32
datasets: # override as needed
  MUSE_news_retain_qa:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left
generation_args:
  max_new_tokens: 32
  stopwords: ["\n\n", "\nQuestion", "Question:"]
