# @package eval.muse.metrics.retain_knowmem_ROUGE
defaults:
  - ../../data/datasets@datasets: MUSE_news_retain_qa
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
  - ../../generation@generation_args: qa_stopwords
handler: rouge
batch_size: 32
datasets: # override as needed
  TOFU_QA_retain_para:
    args:
      predict_with_generate: True
collators:
  DataCollatorForSupervisedDataset: 
    args:
      padding_side: left
